### PR TITLE
Fix issues with snippet showing on incorrect lines

### LINKED ISSUE #235: snippet highlighting wrong lines
I submitted an annotated log for a GCC build error, but the lines I highlighted for the snippet were not preserved correctly.  When I submitted it I highlighted the lines about defining an identifier `bool` as you can see here in this screenshot.

Image

Now when I [view the submission](https://logdetective.com/review/1744217512) it is highlighting completely different lines.

Image

I have [another submission](https://logdetective.com/review/1744231501) that has the same problem.

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #235
Fix https://github.com/fedora-copr/logdetective/issues/241
Fix https://github.com/fedora-copr/logdetective/issues/242

### CODE REVIEW

File: frontend/public/js/offset.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+//   itself.
+// - In Firefox, `previousSibling` can also return the parent node. Also,
+//   in Firefox it skips over text nodes and returns only element nodes.
+//   In Chrome it returns both.
+// - For performance reasons, browsers split long text nodes into multiple
+//   smaller text nodes. In Firefox the length threshold seem to be 65536
+//   characters. I didn't see it happen in Chrome yet.
+// - There are probably many others.
+//
+// The following code is a result of a long vibe coding session with ChatGPT,
```
Comment (TomasTomecek) [inline frontend/public/js/offset.js:14]: LOL

**Review by TomasTomecek — APPROVED** [review]
This is really hard to review so let's merge and try in production :)

How did you enjoy vibe coding with ChatGPT?

**Comment by FrostyX** [comment]
> This is really hard to review so let's merge and try in production :)

I did all my testing by submitting the contribution, then going to the review page for its ID and seeing if the snippets are on correct places. I didn't encounter any wrong ones, but it would be nice if somebody else tried. Especially since we know there are inconsistencies between browser (possibly also operating systems, etc).

> How did you enjoy vibe coding with ChatGPT?

I enjoy the fact it helped me fix the bug, but I am uncomfortable about the fact that I don't really understand the code.

But as for the vibe coding process, not so much. It proved to be viable approach in some circumstances, but to me, it's not fun. I like traditional programming much more.

**Comment by TomasTomecek** [comment]
Just trying these locally (Fedora 42, chrome 135, firefox 137)
First one from Carl is still happening :/ https://github.com/fedora-copr/logdetective-website/issues/235#issue-3013800906
dtto the second one
https://github.com/fedora-copr/logdetective/issues/241 also incorrect :/
https://github.com/fedora-copr/logdetective/issues/242 as well incorrect

**Comment by FrostyX** [comment]
Sorry, I had to force-push. There were many merge conflicts with main that I needed to fix.
